### ISSUE TITLE
What's "Command failed: Not found"

### ISSUE THREAD

**Issue by chuacw** [openwrt/odhcp6c#59]
I ran this command:

`odhcp6c -s /lib/netifd/dhcpv6.script -Ntry -P0 -t120 eth1.2`

I got this response:
> Command failed: Not found

Can the code be improved to specify what is "Not found"? What is the something that is not found?

**Comment by dedeckeh** [comment]
The trace is generated by one of the ubus calls in the dhcpv6 script; nothing can be done in the odhcp6c code to fix this trace

**Comment by brianjmurrell** [comment]
I get this also and the interface does not get it's assigned address.

Any clues how to debug this in ubus?

**Comment by dedeckeh** [comment]
You can add logger statements in the dhcv6 script to find out which cmd triggers this trace

**Comment by brianjmurrell** [comment]
I already did.  The problem is that `$INTERFACE` is not always set and the script ends up with ubus calls where `interface: ""`.

But fixing this didn't actually resolve my root issue which is that my `wan6` interface is getting a `/56` subnet delegated to it with DHCP-PD, and `odhcpd` is successfully announcing a `/64` from it to the LAN but OpenWRT is not configuring itself an address from the subnet.  It used on on 18.06.

**Comment by teknoraver** [comment]
still present:
```
root@router:/# odhcp6c wan835
Command failed: Not found
```
